package connectivity.ws.operations;

/**
 * This class is generated automatically.  Manual edits must be outside of the tagged
 * areas (for example, "START:CLASS:..." and "END:CLASS:...").  Changes within the
 * tag areas will be overwritten when the web service operation is regenerated.
 * Last generated by Orchestration Designer at: 21 ИЮЛЯ 2020 Г. 7:08:14 MSK
 */
public class closeClaim extends com.avaya.sce.runtime.connectivity.restws.CallService {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

    /**
    * Constructor for closeClaim.
    */
    public closeClaim( com.avaya.sce.runtimecommon.IRuntimeSession mySession ) {
		//{{START:CLASS:CONSTRUCTOR
        super(mySession);

        //Web Service
        setServiceName("closeClaim");
		setHttpMethod("POST");
		setOutputFormat("String");
		setUseQuery("true");
		setUseJavaObject("true");
		setUseBody("false");
        setTimeoutSecondsFromParameter("closeMyClaim_1595304494151TimeoutSeconds");
        setEndpointFromParameter("closeMyClaim_1595304494151EndpointUrl");
        setAuthenticationFromParameter("closeMyClaim_1595304494151Authentication");
        setPasswordFromParameter("closeMyClaim_1595304494151Password");
        setUsernameFromParameter("closeMyClaim_1595304494151Username");
        setPreemptiveFromParameter("closeMyClaim_1595304494151Preemptive");
        setSecurityFromParameter("closeMyClaim_1595304494151Security");
        setPortFromParameter("closeMyClaim_1595304494151Port");

        //Operation
        setOperation(new javax.xml.namespace.QName("", "listClaim_OP"));

        //Input parameters
        {
            com.avaya.sce.runtime.connectivity.restws.WsParam param1 = new com.avaya.sce.runtime.connectivity.restws.WsParam(new javax.xml.namespace.QName("id"));
            param1.setWrapped(false);
            param1.setParamType(2);
            param1.setDDVariableName("request:claim_id");
            addInParameter(param1);
        }
        {
            com.avaya.sce.runtime.connectivity.restws.WsParam param1 = new com.avaya.sce.runtime.connectivity.restws.WsParam(new javax.xml.namespace.QName("close"));
            param1.setWrapped(false);
            param1.setParamType(2);
            param1.setDDVariableName("request:action");
            addInParameter(param1);
        }

        //Output parameters
        {
            com.avaya.sce.runtime.connectivity.restws.WsParam param1 = new com.avaya.sce.runtime.connectivity.restws.WsParam(new javax.xml.namespace.QName("(ALL)"));
            param1.setWrapped(false);
            param1.setParamType(0);
            param1.setDDVariableName("response:all");
            addOutParameter(param1);
        }
		setMessageBody("");
        //}}END:CLASS:CONSTRUCTOR
















    }

}

