package connectivity.ws.operations;

/**
 * This class is generated automatically.  Manual edits must be outside of the tagged
 * areas (for example, "START:CLASS:..." and "END:CLASS:...").  Changes within the
 * tag areas will be overwritten when the web service operation is regenerated.
 * Last generated by Orchestration Designer at: 20 ИЮЛЯ 2020 Г. 18:28:28 MSK
 */
public class listClaim extends com.avaya.sce.runtime.connectivity.restws.CallService {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

    /**
    * Constructor for listClaim.
    */
    public listClaim( com.avaya.sce.runtimecommon.IRuntimeSession mySession ) {
		//{{START:CLASS:CONSTRUCTOR
        super(mySession);

        //Web Service
        setServiceName("listClaim");
		setHttpMethod("GET");
		setOutputFormat("String");
		setUseQuery("true");
		setUseJavaObject("true");
		setUseBody("false");
        setTimeoutSecondsFromParameter("listClaim_1595258907636TimeoutSeconds");
        setEndpointFromParameter("listClaim_1595258907636EndpointUrl");
        setAuthenticationFromParameter("listClaim_1595258907636Authentication");
        setPasswordFromParameter("listClaim_1595258907637Password");
        setUsernameFromParameter("listClaim_1595258907637Username");
        setPreemptiveFromParameter("listClaim_1595258907637Preemptive");
        setSecurityFromParameter("listClaim_1595258907637Security");
        setPortFromParameter("listClaim_1595258907637Port");

        //Operation
        setOperation(new javax.xml.namespace.QName("", "listClaim_OP"));

        //Input parameters

        //Output parameters
        {
            com.avaya.sce.runtime.connectivity.restws.WsParam param1 = new com.avaya.sce.runtime.connectivity.restws.WsParam(new javax.xml.namespace.QName("(ALL)"));
            param1.setWrapped(false);
            param1.setParamType(0);
            param1.setDDVariableName("response:all");
            addOutParameter(param1);
        }
		setMessageBody("");
        //}}END:CLASS:CONSTRUCTOR











    }

}

