package connectivity.ws.operations;

/**
 * This class is generated automatically.  Manual edits must be outside of the tagged
 * areas (for example, "START:CLASS:..." and "END:CLASS:...").  Changes within the
 * tag areas will be overwritten when the web service operation is regenerated.
 * Last generated by Orchestration Designer at: 21 ИЮЛЯ 2020 Г. 10:22:51 MSK
 */
public class takeClaim extends com.avaya.sce.runtime.connectivity.restws.CallService {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

    /**
    * Constructor for takeClaim.
    */
    public takeClaim( com.avaya.sce.runtimecommon.IRuntimeSession mySession ) {
		//{{START:CLASS:CONSTRUCTOR
        super(mySession);

        //Web Service
        setServiceName("takeClaim");
		setHttpMethod("POST");
		setOutputFormat("String");
		setUseQuery("true");
		setUseJavaObject("true");
		setUseBody("false");
        setTimeoutSecondsFromParameter("closeClaim_1595316171367TimeoutSeconds");
        setEndpointFromParameter("closeClaim_1595316171367EndpointUrl");
        setAuthenticationFromParameter("closeClaim_1595316171367Authentication");
        setPasswordFromParameter("closeClaim_1595316171367Password");
        setUsernameFromParameter("closeClaim_1595316171367Username");
        setPreemptiveFromParameter("closeClaim_1595316171367Preemptive");
        setSecurityFromParameter("closeClaim_1595316171367Security");
        setPortFromParameter("closeClaim_1595316171367Port");

        //Operation
        setOperation(new javax.xml.namespace.QName("", "listClaim_OP"));

        //Input parameters
        {
            com.avaya.sce.runtime.connectivity.restws.WsParam param1 = new com.avaya.sce.runtime.connectivity.restws.WsParam(new javax.xml.namespace.QName("action"));
            param1.setWrapped(false);
            param1.setParamType(1);
            param1.setDDVariableName("request:action");
            addInParameter(param1);
        }
        {
            com.avaya.sce.runtime.connectivity.restws.WsParam param1 = new com.avaya.sce.runtime.connectivity.restws.WsParam(new javax.xml.namespace.QName("msisdn"));
            param1.setWrapped(false);
            param1.setParamType(1);
            param1.setDDVariableName("request:msisdn");
            addInParameter(param1);
        }

        //Output parameters
        {
            com.avaya.sce.runtime.connectivity.restws.WsParam param1 = new com.avaya.sce.runtime.connectivity.restws.WsParam(new javax.xml.namespace.QName("(ALL)"));
            param1.setWrapped(false);
            param1.setParamType(0);
            param1.setDDVariableName("response:all");
            addOutParameter(param1);
        }
		setMessageBody("");
        //}}END:CLASS:CONSTRUCTOR




    }

}

