<$/////////////////////////////////////////////////////////////////////////////////////////////////////////
// The content of this template is intended to modified by developers to customize code generated by
// Orchestration Designer. Most of the code in this file is in standard JSP syntax except for a few spots 
// which would be pointed out by in-line comments.
// This template works for all Form nodes including Collect and Announce.
// NOTE: if this file name has "Sample" in it, it is a parent template file for OD to use to generate working
//		templates. Don't touch it unless you want to change it for all the subsequently generated templates.
//
////////////////////////////////////////////////////////////////////////////////////////////////////////

// The $ tags used thoughout the JSP page is reserved for enclosing logic that the OD code generator processes. 
// Logic inside the tags works with the project properties configured at design time and apply them to the generated JSP page.
// Don't touch it unless you want to change the default behavior of how project properties apply to the JSP pages.
$>
<$ IForm form = (IForm)argument; 
	String theme = (String)form.getProperty("theme");
	String themeSwatch = (String)form.getProperty("swatch");
	if (themeSwatch == null){
		themeSwatch = "";
	}
	String[] cssFiles = (String[])form.getProperty("cssfiles");
	String[] jsFiles = (String[])form.getProperty("jsfiles");
	boolean useJquery = (boolean)form.getProperty("usejquery");
	String backBtnLabelId = (String)form.getProperty("backbuttonlabel");
	String nextBtnLabelId = (String)form.getProperty("nextbuttonlabel");
	String mapType = (String)form.getProperty("maptype");
	boolean hideBackButton = (boolean)form.getProperty("hidebackbutton");
$>
<%@ page language="java" contentType="text/html; charset=UTF-8"%>
<%@ page import="com.avaya.sce.runtime.*, com.avaya.sce.runtime.html.genmodel.*, com.avaya.sce.runtimecommon.*, java.util.*" %>
<% response.addHeader("X-Frame-Options", "SAMEORIGIN"); %>
<%SCESession mySession = (SCESession)request.getAttribute("session");%>
<!DOCTYPE html> 
<html> 
<head> 
	<title>OD Web Form</title>	
	<meta name="viewport" content="width=device-width, initial-scale=1"> 
	<$ for (String file : cssFiles){ $>
	<link rel="stylesheet" href="<$=file$>"/>
	<$}$>
	<link rel="stylesheet" href="css/avaya.css"/>
	<$ if (useJquery){ $>
	<script src="js/jquery.js"></script>
	<$ } $>
	<$ for (String file : jsFiles){ $>
	<script src="<$=file$>"></script>
	<$}$>
	<script src="js/avaya.js"></script>
	<$ if (useJquery){ $>
	<script src="js/jquery.mobile.avayamsg.js"></script>
	<script src="js/jquery.validate.js"></script>
	<% if (!mySession.getCurrentLanguage().equals("english")) { %>
	<script src="<%=mySession.getCurrentLanguage()%>/jquery.validate.messages.js"></script>
	<% } %>
	<$ } $>
</head>
<body>

<div data-role="page" data-theme="<$=themeSwatch$>">
	<%
	// Javascript for validating input values and displaying the "invalid" message.
	%>
	<script type='text/javascript'>
     	$(document).ready(function() { 
			$('#form1').validate();
			if ($("#message")){
				$("#message").avayaMessage();
			}
		});
	</script>	
	<%
	//Logic to display error message when Set Web Error item is used in Data node.
	String message = mySession.getVariable("ddLastException").getComplexVariable().getField("message").getStringValue();
	if (message.length() > 0){
	%>
		<div id="message"><%=message%></div>
	<%
	}
	%>	
	<div data-role="content" data-theme="<$=themeSwatch$>">
	<$ 
		// The logic below works with the flow node properties:
		// Graphic, Graphic Style, Title Message, Message Style
		String graphic = (String)form.getProperty(WebForm.PROP_GRAPHIC);
		String titleMsg = (String)form.getProperty(WebForm.PROP_TITLE_MSG);
		String graphicStyle =  (String)form.getProperty(WebForm.PROP_GRAPHIC_STYLE);
		if (graphicStyle.length() > 0){
			graphicStyle = "style=\"" + graphicStyle + "\"";
		}
		String titleMsgStyle = (String)form.getProperty(WebForm.PROP_TITLE_MSG_STYLE);
		if (titleMsgStyle.length() > 0){
			titleMsgStyle = "style=\"" + titleMsgStyle + "\"";
		}
		if (graphic != null && !graphic.equals("")){
	$>
		<div style=" text-align:center;margin-left:0 auto;margin-right:0 auto;">
			<img src="<$=graphic$>"/>
		</div>
		<br>
	<$}$>
	<$ if (titleMsg != null && !titleMsg.equals("")){ $>
		<p><$=titleMsg$></p>
		<br>
	<$}$>
<%//writePrompt
/////////////////////////////////////////////////////////////////////////////////////////////////////////
//		Jsp method to display prompt element dynamically. The way a prompt is displayed on the web
// 		page is all dictated by this method.
////////////////////////////////////////////////////////////////////////////////////////////////////////
%>
<%!
	private void writeElement(SCESession mySession, PromptElement element, JspWriter out) throws Exception{
		if (element.getType() == PromptElement.WEB_LOOP_VAR_COLL){
			PromptLoopElement loopElement = (PromptLoopElement)element;
			IVariable variable = mySession.getVariable(loopElement.getValue());
			ICollection collection = variable.getCollection();
			while(collection.hasMore()){
				for (PromptElement promptElem : loopElement.getChildren()){
					writeElement(mySession, promptElem, out);
				}
				collection.next();
			}
			for (PromptElement promptElem : loopElement.getChildren()){
				writeElement(mySession, promptElem, out);
			}
			collection.reset();
			collection.next();
		}
		if (element.getType() == PromptElement.HTMLTEXTELEMENT){
			out.println(element.getValue());
		}
		if (element.getType() == PromptElement.WEBELEMENT){
			String value = mySession.getVariableFieldValue(element.getValue());		
    		out.println("<label>" + element.getLabel() + "</label>");
   			if (element.getWebElemType().equals("Picture")){
   				value = element.getFileURLValue();
   				int width = element.getWidth();		   				
   				int height = element.getHeight();
   				if (width == 0 || height == 0){
   	    			out.println("<div><img src=\"" + value + "\"/></div>");
   	    		}else{
   	    			out.println("<div><img src=\"" + value + "\" width=\"" + width + "\" height=\"" + height + "\"/></div>");
   				}
   	    	} else if (element.getWebElemType().equals("Video")){
   	    		value = element.getFileURLValue();
   	    		int width = element.getWidth();		   				
   				int height = element.getHeight();
   				String controls = element.getAVControls();
   				if (width == 0 || height == 0){
   					out.println("<div><video " + controls + " src=\"" + value + "\"/></div>");
   				}else{
   					out.println("<div><video " + controls + " src=\"" + value + "\" width=\"" + width + "\" height=\"" + height + "\"/></div>");
   				}
   	    	} else if (element.getWebElemType().equals("Voice")){
   	    		value = element.getFileURLValue();
   	    		String controls = element.getAVControls();
   	    		out.println("<div><audio " + controls + " src=\"" + value + "\"/></div>");
   	    	} else if (element.getWebElemType().equals("Map") || element.getWebElemType().indexOf("Map") == 0){
   	    		String protocol = "http";
   	    		if (mySession.getRequest().isSecure()){
   	    			protocol = "https";
   	    		}
   	    		int width = element.getWidth();		   				
   				int height = element.getHeight();
   				if (width == 0) width = 400;
   				if (height == 0) height = 300;
   				String mapAPIKey = mySession.getParameter("mapAPIKey");
   				if (element.getWebElemType().contains("BAIDU")){   					
   					if (mapAPIKey != null && mapAPIKey.length() > 0){
   						mapAPIKey = "&ak=" + mapAPIKey;
   					}else{
   						mapAPIKey = "";
   					}
   					out.println("<div><img src=\"" + protocol + "://api.map.baidu.com/staticimage/v2?center=" + value + mapAPIKey + "&width=" + width + "&height=" + height + "&zoom=16&markers=" + value + "&markerStyles=-1," + protocol + "://api.map.baidu.com/images/marker_red.png\"/></div>");
   				}else if(element.getWebElemType().contains("OTHER")){
   					//For other map type, customers would have to customize the following code to make sure the static map url is generated according to 3rd party API docs.
   					if (mapAPIKey != null && mapAPIKey.length() > 0){
   						mapAPIKey = "&key=" + mapAPIKey;
   					}else{
   						mapAPIKey = "";
   					}
   					out.println("<div><img src=\"" + protocol + "://<domain>/<map url>?center=" + value + mapAPIKey + "&zoom=14&size=" + width + "x" + height + "&markers=color:red%7C" + value + "\"/></div>");   					
   				}else{
   					if (mapAPIKey != null && mapAPIKey.length() > 0){
   						mapAPIKey = "&key=" + mapAPIKey;
   					}else{
   						mapAPIKey = "";
   					}
   					out.println("<div><img src=\"" + protocol + "://maps.googleapis.com/maps/api/staticmap?center=" + value + mapAPIKey + "&zoom=14&size=" + width + "x" + height + "&markers=color:red%7C" + value + "\"/></div>");
   				}
   			} else if (element.getWebElemType().equals("Text")){
   	   			out.println("<input type=\"text\" value=\"" + value + "\" readonly/>");
   			} else if (element.getWebElemType().equals("TextArea")){
   				int width = element.getWidth();		   				
   				int height = element.getHeight();
   				out.println("<textarea rows=\"" + height + "\" cols=\"" + width + "\" readonly/>");
   				out.println(value);
   				out.println("</textarea>");
   			} 
		}
		if (element.getType() == PromptElement.VARIABLE_TEXT){
			String value = mySession.getVariableFieldValue(element.getValue());
			out.println(value);
		}
	}

	public void writePrompt(SCESession mySession, String promptName, TextDisplay.NameType type, JspWriter out) throws Exception{
		//Display prompt elements to show the input value dynamically
		List<PromptElement> elems = TextDisplay.getPromptElements(mySession, promptName, type);			
		for (PromptElement element : elems){
			writeElement(mySession, element, out);
   		}
	}
%>
	<%/////////////////////////////////////////////////////////////////////////////////////////////////////////
	  // Generate UI element from the call flow.
	  // The WebForm object used to get the UI elements is created by the servlet code for the node.
	  // UI is generated by iterate each element in the WebForm object model.
	  // The WebForm object is the mean to preserve the structure built in the flow node editor. 
	  // You can either insert code to change the processing here or you can change the structure by 
	  // overriding/implementing the updateWebForm method in the node's serlvet code.
	  ////////////////////////////////////////////////////////////////////////////////////////////////////////
	%>	
	<% Submit submit = (Submit)request.getAttribute("submit"); %>
	<% WebForm webForm = (WebForm)request.getAttribute("webform"); %>
	<form id="form1" action="<%=(submit != null)?submit.getNext():""%>" method="POST" data-ajax="false" enctype="multipart/form-data">			
	<%if (webForm != null) {
		for (IElement element : webForm.getElements()) {
		if (element instanceof TextDisplay){
			writePrompt(mySession, element.getName(), ((TextDisplay)element).getNameType() ,out);
		}
		if (element instanceof TextInput){
			TextInput textInput = (TextInput)element;			
			String[] props = textInput.getAddtionalProps().toArray(new String[]{});
			String propsStr = "";
			for (String prop : props){
				propsStr += prop + " ";
			}
	%>			
			<div data-role="fieldcontain">
	        	<label for="<%=textInput.getName()%>"><%=webForm.getL18nLabel(textInput.getName(), mySession, textInput.getLabel()) %></label>
	        	<input type="<%=textInput.getType()%>" name="<%=textInput.getName()%>" id="<%=textInput.getName()%>" <%=textInput.getRequired()%> <%=textInput.getMinLengthAttr()%> value="<%=mySession.getVariableFieldValue(textInput.getName())%>" <%=propsStr%> />
			</div>			
	<% }
		if (element instanceof ChoiceInput){
			ChoiceInput choiceInput = (ChoiceInput)element;
			if (choiceInput.getType().equals(ChoiceInput.TYPE_RADIO)){
	%>
				<div data-role="fieldcontain">
					<fieldset data-role="controlgroup">		
					<legend><%=webForm.getL18nLabel(choiceInput.getName(), mySession, choiceInput.getLabel()) %></legend>
				<%
					int cnt = 0;
					String checked = "";
					String value = mySession.getVariableFieldValue(choiceInput.getName());
					if (value.length() == 0){
						checked = "checked";
					}
					String tset = choiceInput.getChoicesTextset();
					String values = choiceInput.getChoiceValues();
					String[] choiceNames = ChoiceInput.getChoiceNames(tset, mySession);
					for (String choice : ChoiceInput.getChoices(values, ChoiceInput.ChoiceType.CHOICEVALUES, mySession)){
						String label = choice; 
						if (cnt < choiceNames.length){
							label = choiceNames[cnt];
						} 
						String id = choiceInput.getName() + "-" + cnt++;
						if (choice.equals(value)){
							checked = "checked";
						}
				%>		
					<input type="radio" name="<%=choiceInput.getName()%>" id="<%=id%>" value="<%=choice%>" <%=checked%>/>
					<label for="<%=id%>"><%=label%></label>
				  <%
				  	checked = "";}
				  %>		
					<%
						String varName = choiceInput.getChoicesVariable();
						if (value.length() == 0){
							checked = "checked";
						}
						String[] choices = ChoiceInput.getChoices(varName, ChoiceInput.ChoiceType.VARIABLE,mySession);
						for (String choice : choices){
							String label = choice; 
							if (cnt < choiceNames.length){
								label = choiceNames[cnt];
							} 							
							String id = choiceInput.getName() + "-" + cnt++;
							if (choice.equals(value)){
								checked = "checked";
							}
						%>
						<input type="radio" name="<%=choiceInput.getName()%>" id="<%=id%>" value="<%=choice%> <%=checked%>"/>
						<label for="<%=id%>"><%=label%></label>
					<%
						checked = "";}
					%>
			    </fieldset>		    
				</div>
			<%
				}else{
			%>
				<div data-role="fieldcontain">
				<label for="<%=choiceInput.getName()%>"><%=webForm.getL18nLabel(choiceInput.getName(), mySession, choiceInput.getLabel())%></label>
				<select name="<%=choiceInput.getName()%>" id="<%=choiceInput.getName()%>">
					<%
					String value = mySession.getVariableFieldValue(choiceInput.getName());
					String checked = "";
					int cnt = 0;
					String tset = choiceInput.getChoicesTextset(); 
					String values = choiceInput.getChoiceValues();
					String[] choiceNames = ChoiceInput.getChoiceNames(tset, mySession);
					for (String choice : ChoiceInput.getChoices(values, ChoiceInput.ChoiceType.CHOICEVALUES, mySession)){
						if (choice.equals(value)){
							checked = "selected";
						}else{
							checked = "";
						}
						String label = choice; 
						if (cnt < choiceNames.length){
							label = choiceNames[cnt];
						}
						cnt++;
					%>
					<option value="<%=choice%>" <%=checked%>><%=label%></option>
					<%
						}
					%>
					
					<%
						String varName = choiceInput.getChoicesVariable();
						String[] choices = ChoiceInput.getChoices(varName, ChoiceInput.ChoiceType.VARIABLE, mySession);
						for (String choice : choices){
							String label = choice; 
							if (cnt < choiceNames.length){
								label = choiceNames[cnt];
							}
							cnt++;
							if (choice.equals(value)){
								checked = "selected";
							}else{
								checked = "";
							}
					%>
						<option value="<%=choice%>" <%=checked%>><%=label%></option>
					<%} %>
				</select>
				</div>
			<%}%>
		 <% } %>
		 <% if (element instanceof LocationInput){
		 		LocationInput input = (LocationInput)element;
		 %>
		 		<div data-role="fieldcontain">
		 		<label for="checkbox-<%=input.getName()%>"><%=webForm.getL18nLabel(input.getName(), mySession, input.getLabel()) %></label>
	        	<input type="checkbox" name="checkbox-<%=input.getName()%>" id="checkbox-<%=input.getName()%>" class="custom" onClick="var loc=new location1('<%=input.getName()%>', location1_<$=mapType$>); loc.getLocation()"/>	        	
	        	<div data-role="collapsible">
   					<h3>Location Details</h3>
   					<input type="text" name="<%=input.getName()%>" id="<%=input.getName()%>" value=""/>
	        		<div id="mapholder-<%=input.getName()%>"></div>
				</div> 
	        	</div>
		 <% } %>
		 
		 <%
		 if (element instanceof PictureInput){
				PictureInput input = (PictureInput)element;
		%>
			<% if (mySession.getProperty("___OD_parameter_web_simulation") != null){ %>
				<div data-role="fieldcontain">
        			<label for="<%=input.getName()%>"><%=webForm.getL18nLabel(input.getName(), mySession, input.getLabel()) %></label>
					<% if (input.getType().equals(PictureInput.TYPE_CAMERA)){ %>
						<input id="<%=input.getName()%>" name="<%=input.getName()%>" type="text" placeholder="Click to Take Picture" onclick="window.open('html/camera.html?id=<%=input.getName()%>', 'Take Picture', 'height=600,width=500')"/>
					<% } %>
					<% if (input.getType().equals(PictureInput.TYPE_VIDEO)){ %>
        			<input id="<%=input.getName()%>" name="<%=input.getName()%>" type="text" placeholder="Click to Record Video" onclick="window.open('html/video.html?id=<%=input.getName()%>', 'Record Video', 'height=600,width=500')"/>
					<% } %>
					<% if (input.getType().equals(PictureInput.TYPE_VOICE)){ %>
        			<input id="<%=input.getName()%>" name="<%=input.getName()%>" type="text" placeholder="Click to Record Audio" onclick="window.open('html/voice.html?id=<%=input.getName()%>', 'Record Audio', 'height=600,width=500')"/>
					<% } %>
				</div>
			<%}else{ %>
				<div data-role="fieldcontain">
        			<label for="<%=input.getName()%>"><%=webForm.getL18nLabel(input.getName(), mySession, input.getLabel()) %></label>
        			<% if (input.getType().equals(PictureInput.TYPE_CAMERA)){ %>
        			<input type="file" name="<%=input.getName()%>" id="<%=input.getName()%>" accept="image/*;capture=camera"/>
					<% } %>
					<% if (input.getType().equals(PictureInput.TYPE_VIDEO)){ %>
        			<input type="file" name="<%=input.getName()%>" id="<%=input.getName()%>" accept="video/*;capture=camcorder"/>
					<% } %>
					<% if (input.getType().equals(PictureInput.TYPE_VOICE)){ %>
        			<input type="file" name="<%=input.getName()%>" id="<%=input.getName()%>" accept="audio/*;capture=microphone"/>
					<% } %>
				</div>	
			<%} %>
		<% } %>
		<%
			if (element instanceof TextAreaInput){
				TextAreaInput input = (TextAreaInput)element;
		%>
			<div data-role="fieldcontain">
	        	<label for="<%=input.getName()%>"><%=webForm.getL18nLabel(input.getName(), mySession, input.getLabel()) %></label>
				<textarea name="<%=input.getName()%>" id="<%=input.getName()%>" rows="<%=input.getRows()%>" cols="<%=input.getCols()%>" <%=input.getRequired()%> ><%=mySession.getVariableFieldValue(input.getName())%></textarea>
			</div>
			
		<% } }%>
					
		<%} %>
		<%
			String backBtnLabel = "Back";
			if ("<$=backBtnLabelId$>".length() > 0){
				backBtnLabel = webForm.getLabelText(mySession, "<$=backBtnLabelId$>").getText();
			}
			String nextBtnLabel = "Next";
			if ("<$=nextBtnLabelId$>".length() > 0){
				nextBtnLabel = webForm.getLabelText(mySession, "<$=nextBtnLabelId$>").getText();
			}			
		%>
		<% String lastPage = (String)mySession.getProperty("___OD_parameter_web_page_last"); 
		   if (lastPage != null){
		%>
		<$ if (!hideBackButton){ $>
			<a onclick="location.href='<%=lastPage%>'" data-role="button" data-icon="arrow-l" data-iconpos="left" data-inline="true"><%=backBtnLabel%></a>
		<$ } $>
		<%} %>
		<$ if (themeSwatch == "") themeSwatch="a"; $>
		<% if (submit != null) {%>
		<button type="submit" data-theme="<$=themeSwatch$>" data-icon="arrow-r" data-iconpos="right" data-inline="true"><%=nextBtnLabel%></button>
		<%} %>	
	</form>	
	</div>
</div>
</body>
</html>
