/**
 * Last generated by Orchestration Designer at: 21 ИЮЛЯ 2020 Г. 7:28:17 MSK
 */
package russian.prompts;

public class closeClaim extends com.avaya.sce.runtime.Prompt {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for closeClaim.
	 */
	public closeClaim() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}


	/**
	 * This method is generated automatically and should not be manually edited
	 * To manually edit the prompt, override:
	 * void updatePrompt()
	 * Last generated by Orchestration Designer at: 21 ИЮЛЯ 2020 Г. 17:11:54 MSK
	 */
	public void buildPrompt(){
		com.avaya.sce.runtime.Format format = null;
		com.avaya.sce.runtime.RenderHint hint = null;
		com.avaya.sce.runtime.MediaPage mediaPage = null;
		setBarginType(com.avaya.sce.runtimecommon.SCERT.BARGIN_SPEECH);
		setName("closeClaim");
		setOrder(com.avaya.sce.runtime.Prompt.STANDARD);

		// Prompt level 1
		setTimeout(1,8000);
		setBargin(1,true);

		com.avaya.sce.runtime.PromptLoopElement ple1 = new com.avaya.sce.runtime.PromptLoopElement("claim:id");
		add(1, ple1);
		ple1.addChild(new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.HTMLTEXTELEMENT,"<p style=\"font-weight:bold\">", null));
		ple1.addChild(new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.HTMLTEXTELEMENT,"Закрыть заявку?", null));
		ple1.addChild(new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.HTMLTEXTELEMENT,"</p>", null));
		ple1.addChild(new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.HTMLTEXTELEMENT,"<p style=\"font-weight:bold\">", null));
		ple1.addChild(new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.HTMLTEXTELEMENT,"#", null));
		format = new com.avaya.sce.runtime.Format();
		format.add(com.avaya.sce.runtime.Format.FORMAT,com.avaya.sce.runtime.Format.FMT_TEXT);
		ple1.addChild(new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.VARIABLE_TEXT,"claim:id", format));
		ple1.addChild(new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.HTMLTEXTELEMENT,"-", null));
		format = new com.avaya.sce.runtime.Format();
		format.add(com.avaya.sce.runtime.Format.FORMAT,com.avaya.sce.runtime.Format.FMT_TEXT);
		ple1.addChild(new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.VARIABLE_TEXT,"claim:topic", format));
		ple1.addChild(new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.HTMLTEXTELEMENT,"</p>", null));
		ple1.addChild(new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.HTMLTEXTELEMENT,"<p>", null));
		format = new com.avaya.sce.runtime.Format();
		format.add(com.avaya.sce.runtime.Format.FORMAT,com.avaya.sce.runtime.Format.FMT_TEXT);
		ple1.addChild(new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.VARIABLE_TEXT,"claim:description", format));
		ple1.addChild(new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.HTMLTEXTELEMENT,"</p>", null));
		ple1.addChild(new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.HTMLTEXTELEMENT,"<p>", null));
		format = new com.avaya.sce.runtime.Format();
		format.add(com.avaya.sce.runtime.Format.FORMAT,com.avaya.sce.runtime.Format.FMT_TEXT);
		ple1.addChild(new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.VARIABLE_TEXT,"claim:status", format));
		ple1.addChild(new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.HTMLTEXTELEMENT,"</p>", null));
		ple1.addChild(new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.HTMLTEXTELEMENT,"<p>", null));
		format = new com.avaya.sce.runtime.Format();
		format.add(com.avaya.sce.runtime.Format.FORMAT,com.avaya.sce.runtime.Format.FMT_TEXT);
		ple1.addChild(new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.VARIABLE_TEXT,"claim:critical", format));
		ple1.addChild(new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.HTMLTEXTELEMENT,"</p>", null));
		ple1.addChild(new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.HTMLTEXTELEMENT,"<hr>", null));
		

	}
}
