<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<RestWebServiceOperation version="1.0">
    <Name>closeMyClaim</Name>
    <ServerUrl>http://127.0.0.1:9090/claim</ServerUrl>
    <EndpointVariable/>
    <HttpMethod>GET</HttpMethod>
    <UseQuery>true</UseQuery>
    <OutputFormat>String</OutputFormat>
    <UseJavaObject>true</UseJavaObject>
    <UseBody>false</UseBody>
    <Operation>
        <Name>listClaim_OP</Name>
        <Inparams>
            <Inparam>
                <Name>msisdn</Name>
                <VariableName>request:msisdn</VariableName>
                <IsWrapper>false</IsWrapper>
                <ShowUnwrapped>false</ShowUnwrapped>
                <ParamType>1</ParamType>
            </Inparam>
            <Inparam>
                <Name>filter</Name>
                <VariableName>request:filter</VariableName>
                <IsWrapper>false</IsWrapper>
                <ShowUnwrapped>false</ShowUnwrapped>
                <ParamType>1</ParamType>
            </Inparam>
        </Inparams>
        <Outprarms>
            <Outparam>
                <Name>(ALL)</Name>
                <VariableName>response:all</VariableName>
                <IsWrapper>false</IsWrapper>
                <ShowUnwrapped>false</ShowUnwrapped>
                <ParamType>0</ParamType>
            </Outparam>
        </Outprarms>
        <Headers/>
    </Operation>
    <WebConfigParameterNames>
        <TimeoutSeconds>listMyClaim_1595303733321TimeoutSeconds</TimeoutSeconds>
        <EndpointUrl>listMyClaim_1595303733321EndpointUrl</EndpointUrl>
        <Authentication>listMyClaim_1595303733321Authentication</Authentication>
        <Password>listMyClaim_1595303733321Password</Password>
        <Username>listMyClaim_1595303733321Username</Username>
        <Preemptive>listMyClaim_1595303733321Preemptive</Preemptive>
        <Security>listMyClaim_1595303733321Security</Security>
        <Port>listMyClaim_1595303733321Port</Port>
    </WebConfigParameterNames>
    <MessageBody/>
    <Keystore/>
    <KeystorePassword/>
</RestWebServiceOperation>
