<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<RestWebServiceOperation version="1.0">
    <Name>listClaim</Name>
    <ServerUrl>http://127.0.0.1:9090/claim</ServerUrl>
    <EndpointVariable/>
    <HttpMethod>GET</HttpMethod>
    <UseQuery>true</UseQuery>
    <OutputFormat>String</OutputFormat>
    <UseJavaObject>true</UseJavaObject>
    <UseBody>false</UseBody>
    <Operation>
        <Name>listClaim_OP</Name>
        <Inparams/>
        <Outprarms>
            <Outparam>
                <Name>(ALL)</Name>
                <VariableName>response:all</VariableName>
                <IsWrapper>false</IsWrapper>
                <ShowUnwrapped>false</ShowUnwrapped>
                <ParamType>0</ParamType>
            </Outparam>
        </Outprarms>
        <Headers/>
    </Operation>
    <WebConfigParameterNames>
        <TimeoutSeconds>listClaim_1595258907636TimeoutSeconds</TimeoutSeconds>
        <EndpointUrl>listClaim_1595258907636EndpointUrl</EndpointUrl>
        <Authentication>listClaim_1595258907636Authentication</Authentication>
        <Password>listClaim_1595258907637Password</Password>
        <Username>listClaim_1595258907637Username</Username>
        <Preemptive>listClaim_1595258907637Preemptive</Preemptive>
        <Security>listClaim_1595258907637Security</Security>
        <Port>listClaim_1595258907637Port</Port>
    </WebConfigParameterNames>
    <MessageBody/>
    <Keystore/>
    <KeystorePassword/>
</RestWebServiceOperation>
