<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<RestWebServiceOperation version="1.0">
    <Name>takeClaim</Name>
    <ServerUrl>http://127.0.0.1:9090/claim</ServerUrl>
    <EndpointVariable/>
    <HttpMethod>POST</HttpMethod>
    <UseQuery>true</UseQuery>
    <OutputFormat>String</OutputFormat>
    <UseJavaObject>true</UseJavaObject>
    <UseBody>false</UseBody>
    <Operation>
        <Name>listClaim_OP</Name>
        <Inparams>
            <Inparam>
                <Name>action</Name>
                <VariableName>request:action</VariableName>
                <IsWrapper>false</IsWrapper>
                <ShowUnwrapped>false</ShowUnwrapped>
                <ParamType>1</ParamType>
            </Inparam>
            <Inparam>
                <Name>msisdn</Name>
                <VariableName>request:msisdn</VariableName>
                <IsWrapper>false</IsWrapper>
                <ShowUnwrapped>false</ShowUnwrapped>
                <ParamType>1</ParamType>
            </Inparam>
        </Inparams>
        <Outprarms>
            <Outparam>
                <Name>(ALL)</Name>
                <VariableName>response:all</VariableName>
                <IsWrapper>false</IsWrapper>
                <ShowUnwrapped>false</ShowUnwrapped>
                <ParamType>0</ParamType>
            </Outparam>
        </Outprarms>
        <Headers/>
    </Operation>
    <WebConfigParameterNames>
        <TimeoutSeconds>closeClaim_1595316171367TimeoutSeconds</TimeoutSeconds>
        <EndpointUrl>closeClaim_1595316171367EndpointUrl</EndpointUrl>
        <Authentication>closeClaim_1595316171367Authentication</Authentication>
        <Password>closeClaim_1595316171367Password</Password>
        <Username>closeClaim_1595316171367Username</Username>
        <Preemptive>closeClaim_1595316171367Preemptive</Preemptive>
        <Security>closeClaim_1595316171367Security</Security>
        <Port>closeClaim_1595316171367Port</Port>
    </WebConfigParameterNames>
    <MessageBody/>
    <Keystore/>
    <KeystorePassword/>
</RestWebServiceOperation>
